djangoCrudApp/crud/urls.py
from django.urls import path
from . import views

app_name = "crud"
urlpatterns = [

    # 一覧
    path("", views.ProductListView.as_view(), name="list"),

    # 新規登録
    path('new/', views.ProductCreateView.as_view(), name='new'),

     # 編集
    path('edit/<int:pk>/', views.ProductUpdateView.as_view(), name='edit'),

      # 削除
    path('delete/<int:pk>/', views.ProductDeleteView.as_view(), name='delete'),
]

djangoCrudApp/djangoCrudApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # CRUD追加
    path('crud/', include('crud.urls')),
]

djangoCrudApp/crud/models.py
from django.db import models
from django.urls import reverse

class Product(models.Model):

    name = models.CharField(max_length=200)
    price = models.IntegerField()

    def __str__(self):
        return self.name

    # 新規登録・編集完了後のリダイレクト先
    def get_absolute_url(self):
        return reverse('crud:list')

djangoCrudApp/crud/views.py
from django.shortcuts import render

from .models import Product
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
# Create your views here.

class ProductListView(ListView):
    """
    一覧
    """

    # 一覧を表示するモデルを指定する
    model = Product

    # 登録項目
    fields = ['name', 'price']

class ProductCreateView(CreateView):
    """
    新規登録
    """

    model = Product

    # 登録項目
    fields = ['name', 'price']

class ProductUpdateView(UpdateView):
    """
    編集
    """

    model = Product

    # 更新項目
    fields = ['name', 'price']

    # テンプレートファイル名の接尾辞の指定
    template_name_suffix = '_update_form'

class ProductDeleteView(DeleteView):
    """
    削除
    """

    model = Product

    # 削除完了後のリダイレクト先
    success_url = reverse_lazy('crud:list')

class ProductListView(ListView):
    """
    一覧
    """

    # 一覧を表示するモデルを指定する
    model = Product

    # 1ページの件数
    paginate_by = 5

djangoCrudApp/crud/templates/crud/product_confirm_delete.html
<h1>削除</h1>

<form method="post">
    {% csrf_token %}

    以下の商品を削除してもよろしいですか？<br>
    {{ object }}<br>

    {{ form }}
    <a href="{% url 'crud:list' %}">戻る</a>
    <input type="submit" value="削除">
</form>

djangoCrudApp/crud/templates/crud/product_form.html
<h1>新規登録</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <a href="{% url 'crud:list' %}">戻る</a>
    <input type="submit" value="登録">
</form>

djangoCrudApp/crud/templates/crud/product_list.html
<h1>商品一覧</h1>

<table border="1">
    <thead>
        <a href="{% url 'crud:new' %}">新規登録</a>
        <tr>
            <td>商品名</td>
            <td>価格</td>
        </tr>
    </thead>
    {% for product in object_list %}
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.price }} 円</td>
        <td>
            <a href="{% url 'crud:edit' pk=product.pk %}">編集</a>
            <a href="{% url 'crud:delete' pk=product.pk %}">削除</a>
        </td>
    </tr>
    {% endfor %}
</table>

{# ページの表示 #}
{{ page_obj.number }} / {{ page_obj.paginator.num_pages }} ページ<br>

{# 前へ #}
{% if page_obj.has_previous %}
<a href="?page=1">&laquo; 先頭</a>
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

{# 次へ #}
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
<a href="?page={{ page_obj.paginator.num_pages }}">最後 &raquo;</a>
{% endif %}

djangoCrudApp/crud/templates/crud/product_update_form.html
<h1>編集</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <a href="{% url 'crud:list' %}">戻る</a>
    <input type="submit" value="編集">
</form>